import type { Metadata } from 'next';
import '../styles/globals.css';
import { lato } from './font';
import { AppProvider } from '@/providers';
import { Roboto_Slab } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const roboto_slab = Roboto_Slab({
  subsets: ['latin'],
  variable: '--font-roboto-slab'
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${roboto_slab.variable} font-lato`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
