import type { Metadata } from "next";
import "./ui/globals.css";
import { lato } from "./ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable}`}>
        {children}
      </body>
    </html>
  );
}
