import type { Metadata } from "next";
import localfont from "next/font/local";
import StoreProvider from "./StoreProvider";
import "./globals.css";

const lato = localfont({
  src: [
    {
      path: '../../public/fonts/Lato-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Lato-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Lato-Italic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../public/fonts/Lato-Semibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Lato-Bold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: "--font-lato"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} font-lato`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
